### ISSUE TITLE
TODO: Ensure failures are compatible with PHP7 behavior

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#1]
See: https://github.com/php/php-src/pull/1398

**Comment by CodesInChaos** [comment]
Feel free to liberally take from my implementation, which already contains a lot of error handling.

I also figured out how to handle the whole range of inputs for `random_int`, so you might want to use the whole function.

https://gist.github.com/CodesInChaos/03f9ea0b58e8b2b8d435

**Comment by paragonie-scott** [comment]
This is almost resolved by https://github.com/paragonie/random_compat/commit/13cc71779e3b9a9b47902ee0da94c57fcb04075a -- just need to tweak the exact error message strings.

@CodesInChaos I adopted some of your code; how does it look?
