### ISSUE TITLE
OpenSSL deprecation warning for v1.4.2

### ISSUE THREAD

**Issue by schnittstabil** [paragonie/random_compat#108]
OpenSSL support was reintroduced with `v1.4`, and is used as an *absolute last resort*.

As an user of an security-related package depending on `random_compat` it would be nice to know if `openssl_random_pseudo_bytes` is actually used (e.g. `v1.4` is used due to composer version constraints).

Triggering some deprecation notice seems reasonable to me – but maybe there are some better alternatives.

**Comment by paragonie-scott** [comment]
The most straightforward solution I can think of without unintended side-effects is:

```php
define('RANDOM_COMPAT_DRIVER', 'openssl');
```

and then in users' code:

```php
if (defined('RANDOM_COMPAT_DRIVER')) {
    if (RANDOM_COMPAT_DRIVER === 'openssl') {
        // You can now check for this.
    }
}
```

I'd be cautious about raising a deprecation notice.

**Comment by schnittstabil** [comment]
> I'd be cautious about raising a deprecation notice.

As not to be misunderstood, I thought about something like
```diff
 $buf = openssl_random_pseudo_bytes($bytes, $secure);
 if (
     $buf !== false
     &&
     $secure
     &&
     RandomCompat_strlen($buf) === $bytes
 ) {
+    trigger_error(
+        'using openssl_random_pseudo_bytes, please install libsodium - or similar',
+        E_USER_NOTICE
+    );
     return $buf;
 }
```

Are there any downsides?  I don't know a lot how `trigger_error` and `set_error_handler` are (mis-)used in the wild?
***
Checking `defined('RANDOM_COMPAT_DRIVER')` only shifts the problem to the next library in the dependency chain (in my case `Slim-Csrf`), because the very end framework/script may not know `random_compat` is used at all.

**Comment by paragonie-scott** [comment]
The downside is that people are going to complain about the `E_NOTICE` causing full path disclosures in their applications (because PCI-DSS auditors usually have a checklist mentality) and they're going to accuse us of introducing vulnerabilities in their application. Even though `display_errors` should be off in production environments.

**Comment by glensc** [comment]
btw, are you absolutely sure the openssl usability can't be runtime detected?

[composer/ca-bundle](https://github.com/composer/ca-bundle/blob/1.0.2/src/CaBundle.php#L176-L279) does such thing, maybe get some ideas how to test it here as well.

**Comment by GrahamCampbell** [comment]
Might be better to put this in 1.5 rather than 1.4.2 if it is done.

**Comment by GrahamCampbell** [comment]
> composer/ca-bundle does such thing, maybe get some ideas how to test it here as well.

It would be good if they could move that function to a separate library so everyone could use it, and keep it secure together.

**Comment by glensc** [comment]
composer/ca-bundle already is separate library

**Comment by paragonie-scott** [comment]
I'm not sure what to do with this ticket. Introducing E_NOTICE errors will cause people to freak out. If anything, do we need to document the difference between v1 and v2 better?

**Comment by schnittstabil** [comment]
I've been hoping one might know some PHP magic (better than triggering an `E_NOTICE`) to inform developers about the deprecation. But I have to conclude, that relying on semversions is absolutely sufficient to lead developers to read about BCs.

> do we need to document the difference between v1 and v2 better

No, [tagged releases](https://github.com/paragonie/random_compat/releases) ftw.

@all Thanks for the effort of looking into it.
