### ISSUE TITLE
Could not generate a random string. Is our OS secure?

### ISSUE THREAD

**Issue by harmenzon** [paragonie/random_compat#109]
Could you please help me out with this error? 
> Could not generate a random string. Is our OS secure?

I have tried to Google for it, but can not find the answer. 
I installed random_compat using composer.
I have linked it with:
`require_once '../vendor/paragonie/random_compat/lib/random.php';`

And used the following code:
```
try {
    $string = random_bytes(32);
} catch (TypeError $e) {
    // Well, it's an integer, so this IS unexpected.
    die("An unexpected error has occurred"); 
} catch (Error $e) {
    // This is also unexpected because 32 is a reasonable integer.
    die("An unexpected error has occurred");
} catch (Exception $e) {
    // If you get this message, the CSPRNG failed hard.
    die("Could not generate a random string. Is our OS secure?");
}
```

**Comment by paragonie-scott** [comment]
What does the following code output?

```php
<?php
var_dump([
    PHP_VERSION,
    ini_get('open_basedir'),
    ini_get('safe_mode'),
    DIRECTORY_SEPARATOR,
    function_exists('mcrypt_create_iv'),
    function_exists('openssl_random_pseudo_bytes'),
    is_readable('/dev/urandom')
]);
```

**Comment by paragonie-scott** [comment]
Note: I've added a section to the README to make the solution easier to find.

https://github.com/paragonie/random_compat#troubleshooting

**Comment by harmenzon** [comment]
`array(7) { [0]=> string(6) "5.6.20" [1]=> string(171) "/var/services/tmp:/etc.defaults:/usr/bin/php:/usr/syno/synoman:/etc:/var/run:/volume1/@tmp/php:/var/services/web:/var/services/photo:/var/services/blog:/var/services/homes" [2]=> bool(false) [3]=> string(1) "/" [4]=> bool(true) [5]=> bool(true) [6]=> bool(false) }`

**Comment by paragonie-scott** [comment]
Okay, your host doesn't have `/dev/urandom` whitelisted by `open_basedir`, so we can't read the kernel's CSPRNG device.

Ask your webhost to add `:/dev/urandom` at the very end of the open_basedir configuration. (If you're the webhost, edit your php.ini file to allow scripts to read this file.)

Strangely, mcrypt can't read `/dev/urandom` if this open_basedir restriction is in effect either. (It's really unfortunate.)

**Comment by harmenzon** [comment]
That solved my problem. Thank you for your help!

**Comment by azteam** [comment]
Hello,

Sorry for reopen this thread. So I have the same issue: the output of the above code:
array(7) {
  [0]=>
  string(6) "5.6.24"
  [1]=>
  string(13) ":/dev/urandom"
  [2]=>
  bool(false)
  [3]=>
  string(1) "/"
  [4]=>
  bool(true)
  [5]=>
  bool(true)
  [6]=>
  bool(true)
}

How to solve our problem?

**Comment by paragonie-scott** [comment]
@azteam Are you in a FreeBSD jail? Only passing ":/dev/urandom" to open_basedir won't fix the problem. You'll need to have your host OS allow you to read from `/dev/urandom` from within the jail.

**Comment by paragonie-scott** [comment]
Closing this as the README has been updated to answer these questions.
