### ISSUE TITLE
Call for review before v1.0.0 is tagged

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#11]
Once #7 can be safely closed (depends on two PRs on `php-src`), we should be 100% compatible with `random_bytes()` and `random_int()`. At such time, I intend to tag `v1.0.0` as the first stable release.

### Three questions:

1. Does anyone have any objections?
2. Would anyone like to request a delay in order to accommodate an in-depth review first?
3. How confident are you that the current implementation is reasonably secure?

Thanks everyone for contributing to this effort to backport `random_bytes()` and `random_int()` for PHP 5 users, and thanks to everyone who worked on the CSPRNG for PHP 7.

**Comment by scottchiefbaker** [comment]
I just wanna say :+1: for all your hard work. I think it's a really solid implementation, and released well before PHP7 is release also. Good work!

**Comment by redragonx** [comment]
First of all, great work!

I have a minor (probably stupid complaint), but here it goes

https://github.com/paragonie/random_compat/blob/master/lib/random.php#L90

This bugs me a lot because at first glance the name doesn't tell you much. I believe it should say $execCount or $numOfExecs. I had to read the function comments twice before I realized what $execs was for, maybe it's just me, but it might look more cleaner with a new name.

**Comment by oittaa** [comment]
Nice job! There's one minor thing I noticed in the tests.

https://github.com/paragonie/random_compat/blob/master/tests/unit/RandomIntTest.php#L16

I think it should be ```random_int(~PHP_INT_MAX, PHP_INT_MAX)``` instead of the current ```random_int(-PHP_INT_MAX + 1, PHP_INT_MAX)```. For example on my system these ```$min``` values are the following:
```
~PHP_INT_MAX = int(-9223372036854775808)
-PHP_INT_MAX + 1 = int(-9223372036854775806)
```

**Comment by geggleto** [comment]
Hi!

I find it rather odd that you are prioritizing mcrypt over the linux rng given that your stance on mcrypt is that it is "Abandonware" ... https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

Affected: https://github.com/paragonie/random_compat/blob/master/lib/random.php#L3-L32

While I am not a security researcher or anything, I would suggest removing all instances of mcrypt.

Excellent work :)

**Comment by paragonie-scott** [comment]
mcrypt_create_iv() is not part of libmcrypt. It's part of PHP's ext/mcrypt
code and it reads from urandom or CryptGenRandom unless you pass
MCRYPT_RAND. It's the only thing labeled mcrypt that I like. :)

**Comment by geggleto** [comment]
thanks for the clarification, one more reason why the PHP API really needs a clean-up :/

**Comment by scottchiefbaker** [comment]
Not sure if it helps or not, but on the docs for `random_bytes()` on [php.net](http://php.net/random_bytes) it says:

```
 The sources of random are as follows:

    On Windows CryptGenRandom() is used exclusively
    arc4random_buf() is used if it is available (generally BSD specific)
    /dev/arandom is used where available
    /dev/urandom is used where none of the above is available
```

I'm not sure if that indicates the order of preference.

**Comment by paragonie-scott** [comment]
That's very similar to what we do. 

`mcrypt_create_iv()` will use `CryptGenRandom()` for Windows (one reason why it's the first priority), then we read `/dev/arandom`, then `/dev/urandom`, and use openssl as a last resort.

Unfortunately, there is no `arc4random_buf()` in PHP.

**Comment by redragonx** [comment]
Why don't you throw exceptions for the other functions when they don't exist? Even though you do throw an exception when there are no good suitable CSPRNG functions.

Is this by a design choice?

**Comment by paragonie-scott** [comment]
> Why don't you throw exceptions for the other functions when they don't exist?

Could you give me an example of what you expect to see instead of what's currently in the repo?

**Comment by redragonx** [comment]
Sure, give me some time.

**Comment by redragonx** [comment]
Actually, what you have is fine.

**Comment by oittaa** [comment]
https://github.com/paragonie/random_compat/blob/master/lib/random.php#L202-L204
Referencing to ```$reject``` doesn't really make sense since it doesn't exist in this version of the function.

This might be nitpicking, but ```$bytes``` is [first](https://github.com/paragonie/random_compat/blob/master/lib/random.php#L213) used to store return value from ```random_bytes()``` function, but [a bit later](https://github.com/paragonie/random_compat/blob/master/lib/random.php#L256) it's used to store how many bytes are need for the smaller range and a new variable called ```$rval``` is used to store return value from ```random_bytes()```. Maybe the variables could be named more consistently?

**Comment by paragonie-scott** [comment]
You're right on both points. Commit incoming. :)

**Comment by oittaa** [comment]
Is there a reason why this test is done twice or is it just an accidental copy&paste?
https://github.com/paragonie/random_compat/blob/master/tests/unit/RandomIntTest.php#L23-L24

**Comment by paragonie-scott** [comment]
Accidental copy&paste.

**Comment by oittaa** [comment]
https://github.com/paragonie/random_compat/blob/master/lib/random.php#L205-L225
What's done there is basically the same as what's done from line 263 onwards. Could that whole block be consolidated perhaps like this:

```
--- random-orig.php	2015-07-13 13:32:06.425644813 +0300
+++ random.php	2015-07-13 14:06:05.025706479 +0300
@@ -187,6 +187,12 @@
         if ($max === $min) {
             return $min;
         }
+
+        /**
+         * Initialize variables to 0
+         */
+        $attempts = $bits = $bytes = $mask = $valueShift= 0;
+
         $range = $max - $min + 1;
 
         /**
@@ -202,58 +208,32 @@
              * The rejection probability is at most 0.5, so this corresponds
              * to a failure probability of 2^-128 for a working RNG
              */
-            for ($attempts = 0; $attempts < 128; $attempts++) {
-                /**
-                 * Generate a random integer...
-                 */
-                $rval = random_bytes(PHP_INT_SIZE);
-                if ($rval === false) {
-                    throw new Exception(
-                        'Random number generator failure'
-                    );
-                }
-                $value = 0;
-                for ($i = 0; $i < PHP_INT_SIZE; ++$i) {
-                    $value = ($value << 8) | ord($rval[$i]);
-                }
-                if ($value >= $min && $value <= $max) {
-                    /**
-                     * This value is within the accepted bounds.
-                     */
-                    return $value;
-                }
-            }
-            throw new Exception(
-                'random_int: RNG is broken - too many rejections'
-            );
-        }
-        /**
-         * We incremented $range earlier to test for overflows
-         */
-        --$range;
-
-        /**
-         * Initialize variables to 0
-         */
-        $attempts = $bits = $bytes = $mask = 0;
+            $bytes = PHP_INT_SIZE;
+            $mask = -1;
+        } else {
+            /**
+             * We incremented $range earlier to test for overflows
+             */
+            --$range;
 
-        $tmp = $range;
-        /**
-         * We want to store:
-         * $bytes => the number of random bytes we need
-         * $mask => an integer bitmask (for use with the &) operator
-         *          so we can minimize the number of discards
-         * 
-         * $bits is effectively ceil(log($range, 2)) without dealing with 
-         * type juggling
-         */
-        while ($tmp > 0) {
-            if ($bits % 8 === 0) {
-               ++$bytes;
+            /**
+             * We want to store:
+             * $bytes => the number of random bytes we need
+             * $mask => an integer bitmask (for use with the &) operator
+             *          so we can minimize the number of discards
+             * 
+             * $bits is effectively ceil(log($range, 2)) without dealing with 
+             * type juggling
+             */
+            while ($range > 0) {
+                if ($bits % 8 === 0) {
+                   ++$bytes;
+                }
+                ++$bits;
+                $range >>= 1;
+                $mask = $mask << 1 | 1;
             }
-            ++$bits;
-            $tmp >>= 1;
-            $mask = $mask << 1 | 1;
+            $valueShift = $min;
         }
 
         /**
@@ -296,14 +276,15 @@
              * Apply mask
              */
             $val &= $mask;
+            $val += $valueShift;
 
             ++$attempts;
             /**
              * If $val is larger than the maximum acceptable number for
              * $min and $max, we discard and try again.
              */
-        } while ($val > $range);
-        return (int) ($min + $val);
+        } while (!is_int($val) || $val > $max || $val < $min);
+        return $val;
     }
 }
 

```

**Comment by paragonie-scott** [comment]
Current blockers:

* #7 ... which is in turn blocked by:
    * https://github.com/php/php-src/pull/1397
    * https://github.com/php/php-src/pull/1398

Does anyone have any suggestions for clearing the path forward?

**Comment by geggleto** [comment]
I really think that if a RNG should emit an exception. I would be building a wrapper around the php functions that do this. In the event of a false being returned, that is a very very big show-stopper for anything that needs to be secure. The application needs to halt and an error raised and logged.

I guess what you can do is wrap around the php functions to include the functionality we think is right. There is no guarantee that the internal developers will have the same mind-set.

**Comment by paragonie-scott** [comment]
I suppose we should rope in @narfbg and see what he thinks about breaking compatibility with 7.0.x in favor of compatibility of a wiser decision in 7.1.x should internals decide to do the insecure thing.

I really don't want to be forced to do things badly.

**Comment by narfbg** [comment]
Here's what I found during my review: https://github.com/paragonie/random_compat/pull/22#issuecomment-128324073

On compatibility with PHP 7.0:

I don't think it's fair to ask this question until the PHP internals decision is made, but I believe any *compat* package should follow the language's behavior, regardless of some of its possible stupidities. At the end of the day, your main goal here is to ease the transition to PHP7 and if there's conflicting behavior, you're not helping anyone.
Your users would get used to `try ... catch` blocks with this package and if internals decide to just return `false` instead, the same people that you're trying to help may just end up harder to find bugs - more harm done, no matter how good your intention was.

If internals does make the bad decision (returning `false`) and you can't come to peace with that, you'd do far better with a generic wrapper that covers 7.0 too.

My €0.02 ;)

**Comment by geggleto** [comment]
@paragonie-scott after some deliberation, I came to this conclusion. You can keep this repo as an exact copy in all its "glory", and then just simply create another repo that fixes all the mistakes in a wrapper ;) Then those of us who like things "more correct" can just use the wrapper and those who want the drop in replacement can use it. 

No sense arguing about which one to do, lets just do both and let the community decide how they want it.

**Comment by paragonie-scott** [comment]
So you're suggesting we fork our own project into, say, random_compat and
secure_random, if the internals development team nosedives into the worst
of all possible outcomes?

On Aug 6, 2015 8:27 AM, "Glenn Eggleton" <notifications@github.com> wrote:
>
> @paragonie-scott after some deliberation, I came to this conclusion. You
can keep this repo as an exact copy in all its "glory", and then just
simply create another repo that fixes all the mistakes in a wrapper ;) Then
those of us who like things "more correct" can just use the wrapper and
those who want the drop in replacement can use it.
>
> No sense arguing about which one to do, lets just do both and let the
community decide how they want it.

**Comment by geggleto** [comment]
@paragonie-scott Yes.

**Comment by redragonx** [comment]
But what's the point of forking to support "bad practice" wrapper code if the goal of this project was mainly about PHP 5? Why should people keep thinking that it's ok to use the wrapper repo for future PHP versions? PHP 7 should push for exceptions since PHP 7 is all about new code paradigms (At least to me that is.)

**Comment by paragonie-scott** [comment]
https://wiki.php.net/rfc/random-function-exceptions

The fate of the v1.0.0 of this project is in the hands of the PHP internals team. I already have the security downgrade (and secure_random wrapper) written, but not committed or pushed to Github yet.

**Comment by geggleto** [comment]
thanks for the update @paragonie-scott :)

**Comment by paragonie-scott** [comment]
https://wiki.php.net/rfc/random-function-exceptions passed 28-2.
