### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [paragonie/random_compat#114]
You should consider signing git commits & releases.

* https://github.com/micahflee/onionshare/issues/221#issuecomment-220317661
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/

**Comment by paragonie-scott** [comment]
:+1:

We do this for our other projects already. See https://github.com/paragonie/halite/releases from earlier today.

**Comment by paragonie-scott** [comment]
The next tags/releases will be signed by our PGP key.
