### ISSUE TITLE
Which version should we use ?

### ISSUE THREAD

**Issue by mickaelandrieu** [paragonie/random_compat#116]
Hi,
I just noticed the PHP requirements as the same for 1.4 and 2.0.

What are the differences between the major versions ?

Mickaël

**Comment by paragonie-scott** [comment]
Version 1.x will fallback to OpenSSL, version 2.x will not.

See #96 and https://github.com/ramsey/uuid/issues/80 -- version 2 is more secure.

**Comment by mickaelandrieu** [comment]
PrestaShop users are mostly non technical people totaly unable to fix a technical issue, `1.4+` should be used by default (because it should work "as it") and `2.x` should be suggested (more secure).

Thank you @paragonie-scott !
