### ISSUE TITLE
Can't install with Laravel 5.3

### ISSUE THREAD

**Issue by 1dnmr** [paragonie/random_compat#117]
composer require baopham/dynamodb:0.3.0 return

Error log:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for baopham/dynamodb 0.3.0 -> satisfiable by baopham/dynamodb[0.3.0].
    - Conclusion: remove paragonie/random_compat v2.0.2
    - Conclusion: don't install paragonie/random_compat v2.0.2
    - baopham/dynamodb 0.3.0 requires paragonie/random_compat ^1.1 -> satisfiable by paragonie/random_compat[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1].
    - Can only install one of: paragonie/random_compat[1.1.0, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.1, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.2, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.3, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.4, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.5, v2.0.2].
    - Can only install one of: paragonie/random_compat[1.1.6, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.2.0, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.2.1, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.2.2, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.2.3, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.3.0, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.3.1, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.4.0, v2.0.2].
    - Can only install one of: paragonie/random_compat[v1.4.1, v2.0.2].
    - Installation request for paragonie/random_compat (locked at v2.0.2) -> satisfiable by paragonie/random_compat[v2.0.2].

**Comment by paragonie-scott** [comment]
> - baopham/dynamodb 0.3.0 requires paragonie/random_compat ^1.1 -> satisfiable by paragonie/random_compat[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1].

They need to update their requirements from `^1.1` to `^1.4|^2`.

**Comment by 1dnmr** [comment]
Thank you for quick reply, Scott!

**Comment by paragonie-scott** [comment]
https://twitter.com/ParagonIE/status/776096550103625728 - for everyone else's future reference :)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/856e858ab44b76ae67d8f8398d496a7464ac4656
