### ISSUE TITLE
Why are your design decisions named errata?

### ISSUE THREAD

**Issue by rugk** [paragonie/random_compat#119]
As far as [I saw](https://en.wikipedia.org/wiki/Erratum) "errata" is just a correction of a scientific paper. In this case here this makes no sense.
Also the other explanations [shown on Wikipedia](https://en.wikipedia.org/wiki/Errata_%28disambiguation%29) make no sense, so why do you name it "Errata"?

**Comment by paragonie-scott** [comment]
A shorthand I picked up from Dungeons and Dragons and probably misapplied.

**Comment by rugk** [comment]
Hmm, so what to do now?

**Comment by paragonie-scott** [comment]
We could rename it to something else; that's not really a breaking change.

**Comment by rugk** [comment]
Surely nobody parses the Errata file :laughing:, yes. We just need a good new name.

**Comment by ivantcholakov** [comment]
Maybe Rationale?
https://en.wikipedia.org/wiki/Design_rationale

**Comment by paragonie-scott** [comment]
Renamed. v2.0.4 will have this correction.

**Comment by hipio** [comment]
It seems that the link in the article `How to Securely Generate Random Strings and Integers in PHP` has not been updated. It still contains a link to the old `ERRATE.md`-file.

**Comment by paragonie-scott** [comment]
Thanks, I'll fix that in the next update.
