### ISSUE TITLE
Changed extension name for "libsodium"

### ISSUE THREAD

**Issue by MaSpeng** [paragonie/random_compat#132]
With release of version 2.0 at 13. July 2017 `libsodium-php`have changed the name of the php extension from `libsodium` to `sodium`.

@see https://github.com/jedisct1/libsodium-php/blob/master/README.md.

Please adapt these change in the library.

**Comment by paragonie-scott** [comment]
The new version requires PHP 7. Random_compat is a NOP on PHP 7 and higher, since it only polyfills these functions.

**Comment by glensc** [comment]
Juli -> July (English fix)

**Comment by jedisct1** [comment]
There has to be be a PECL option to force a specific version, right?

**Comment by MaSpeng** [comment]
@paragonie-scott thanks for the hint. Then it might be good to clarify the version constrain for php and add `<7.0`?

**Comment by paragonie-scott** [comment]
random_compat has to be safe to include in software that targets PHP 5 and PHP 7. If your framework targets both, and we stop at PHP < 7, it will break installs.

**Comment by MaSpeng** [comment]
Ok thanks for your advice.
