### ISSUE TITLE
Fatal error: Undefined constant '' [....]/vendor/paragonie/random_compat/lib/error_polyfill.php on line 32

### ISSUE THREAD

**Issue by HarryWiles** [paragonie/random_compat#137]
I'm (still) on php5.6. Any ideas?

`Fatal error: Undefined constant '' [....]/vendor/paragonie/random_compat/lib/error_polyfill.php on line 32`

**Comment by paragonie-scott** [comment]
I have no idea. What version do you have installed?

**Comment by paragonie-scott** [comment]
I've never heard of an `Fatal error: Undefined constant ''` error before. If this is still a problem, please let me know and I'll try to debug it further. For the time being, however, I'm going to close the issue as it seems unrelated to anything we're doing.
