### ISSUE TITLE
Weird tag

### ISSUE THREAD

**Issue by theofidry** [paragonie/random_compat#142]
Is this intentional? https://github.com/paragonie/random_compat/releases/tag/v9.99.99

**Comment by pxgamer** [comment]
Afaik it is. See #140 👍

Looks like it's so that:
- When using `^2` as a requirement, it won't break semver.
- When using `>=1` or `>=2` or `*` it will use `v2.*` for PHP 5 and `v9.*` for PHP 7 only.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat#version-conflict-with-other-php-project this is documented in the README :)

**Comment by theofidry** [comment]
Thanks :)
