### ISSUE TITLE
version v9.99.99 

### ISSUE THREAD

**Issue by Webonaute** [paragonie/random_compat#143]
this is creating confusion in composer packaging. is it possible to remove that version that seem odd?

**Comment by paragonie-scott** [comment]
See https://github.com/paragonie/random_compat#version-conflict-with-other-php-project

**Comment by paragonie-scott** [comment]
See #142 for previous discussion

**Comment by Webonaute** [comment]
so what do I do if I can't install v9.99.99 because lower version is use in dependencies?

**Comment by Webonaute** [comment]
friendsofsymfony/user-bundle  v2.1.2  requires  paragonie/random_compat (^1 || ^2)   
ramsey/uuid                   3.7.3   requires  paragonie/random_compat (^1.0|^2.0)  
symfony/polyfill-php70        v1.8.0  requires  paragonie/random_compat (~1.0|~2.0)

**Comment by paragonie-scott** [comment]
Set your require string to `>= 1 < 9.99`, and tell other libraries to set theirs to `>= 1`

**Comment by Webonaute** [comment]
why not asking ppl to just put in composer this snippet on PHP7+ :

```
    "replace": {
        "paragonie/random_compat": "*"
    },
```

its more simple than managing weird versioning.

**Comment by paragonie-scott** [comment]
"Sure why not?" is the only thing that comes to mind.

Generally, you don't want to run version 1. Some projects insist on still using it (IMHO, "We trust OpenSSL's userspace PRNG as much as the kernel's CSPRNG" is rather silly).

You want version 2, for PHP 5 compatible projects.

You want version 9.99.99 to be installable if you're PHP 7-only but one of your dependencies requires random_compat. This makes IDEs not puke over duplicate class/function definitions, and reduces bloat.

**Comment by Webonaute** [comment]
"replace" method prevent package to be downloaded at all so for me, no complain in IDE and 1 less package to download = deploy faster :D!

**Comment by glensc** [comment]
i found "replace" solution more ellegant. but, i ran into some odd issues when such was seen in second level package. i.e library.

i have only commit message. you may figure out the details yourself:
```
commit a034bdf7419b8b656070f94c1b49a2ef37e7e50b
Author: Elan Ruusamäe <glen@delfi.ee>
Date:   Mon Dec 4 15:16:23 2017 +0200

    composer: remove "replace" directives

    these confuse dependency resolution and should be avoided in libraries

diff --git a/composer.json b/composer.json
index d5979b9..e270094 100644
--- a/composer.json
+++ b/composer.json
@@ -26,9 +26,6 @@
             "ED\\EventForwarder\\Test\\": "tests/"
         }
     },
-    "replace": {
-        "symfony/polyfill-mbstring": "1.6.0"
-    },
     "require": {
         "php": "^5.3.0 || ^7.0",
         "ext-mbstring": "*",
```

**Comment by paragonie-scott** [comment]
Given the issue @glensc raised, I'm not sure if "replace" will work.

**Comment by paragonie-scott** [comment]
I've added a dedicated anchor to the README, which should resolve any confusion anyone has with v9.99.99.

https://github.com/paragonie/random_compat#version-99999

**Comment by glensc** [comment]
@paragonie-scott the issue i reported, happens if it's applied to a library. it's perfectly fine to apply to top level composer project.

so:
- don't apply it in `paragonie/random_compat`
- apply in `blah/myproject`

**Comment by rafaeltovar** [comment]
Installation of `paragonie/random-lib` is broken about this.

```sh
$ composer require paragonie/random-lib

Using version ^2.0 for paragonie/random-lib                                           
./composer.json has been updated

Loading composer repositories with package information
Updating dependencies (including require-dev)                                         

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install paragonie/random-lib v2.0.1
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Installation request for paragonie/random-lib ^2.0 -> satisfiable by paragonie/random-lib[v2.0.0, v2.0.1].
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - paragonie/random-lib v2.0.0 requires paragonie/random_compat ^2 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.18, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].

Installation failed, reverting ./composer.json to its original content.
```

My PHP version is:

```sh
$ php -v
PHP 7.1.24-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:23:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.24-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by jdreesen** [comment]
Please use `composer require paragonie/random_compat:\>=2`, as stated in the `Installing` section of the readme.

But as you're on PHP 7, which has native support for this, there's no polyfill needed, so why do you want to install it anyways?

**Comment by rafaeltovar** [comment]
> Please use `composer require paragonie/random_compat:\>=2`, as stated in the `Installing` section of the readme.
> 
> But as you're on PHP 7, which has native support for this, there's no polyfill needed, so why do you want to install it anyways?

Thanks!!. I don't want install `paragonie\random_compat`, but I want to use `paragonie\random-lib` like a secure random string generator, and this is a dependency.

**Comment by joelharkes** [comment]
@Webonaute  i would agree

```
    "replace": {
        "paragonie/random_compat": "*"
    },
```
is best solution for php7 projects
