### ISSUE TITLE
please remove v9.99.99

### ISSUE THREAD

**Issue by smecnarowski** [paragonie/random_compat#146]
Thanks a lot :)

**Comment by jcoby** [comment]
This seems to be on purpose. See https://github.com/paragonie/random_compat/commit/35469243ebbb9be5086cff57538cac6da2c36852

Which later got re-versioned to v9.99.99.

And the code is a noop in the branch: https://github.com/paragonie/random_compat/tree/v9.99.99

**Comment by paragonie-scott** [comment]
Correct. We will not be removing v9.99.99.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat#version-99999 - Please read this if you are encountering problems due to the existence of v9.99.99.

**Comment by smecnarowski** [comment]
I'm Sorry for this misunderstanding, - now i see that this is required for ramsey/uuid and v 9.99.99 is in their composer.json https://github.com/ramsey/uuid/blob/3.x/composer.json

**Comment by paragonie-scott** [comment]
Permanent link:

https://github.com/ramsey/uuid/blob/d09ea80159c1929d75b3f9c60504d613aeb4a1e3/composer.json#L29

This is correct: The library is permitting v9.99.99 or v2.x or v1.x. It's equivalent to `>= 1`.

If you're creating your `composer.lock` on PHP 7 but deploying it on PHP 5, you'll probably run into incompatibility issues. Workaround: Explicitly use `>=1 <9` or `>=2 <9` in your own project's `composer.json` file.

**Comment by IMM0rtalis** [comment]
Even with the info section I still dont understand why it is needed. I did not see it anywhere else yet. Why not just v1 for php5 and >=v2 for php7 ? What is the exact benefit of having it like 9.99.99?
