### ISSUE TITLE
php_warning -> "Message: is_readable(): open_basedir restriction in effect."

### ISSUE THREAD

**Issue by voku** [paragonie/random_compat#15]
Message: is_readable(): open_basedir restriction in effect. File(/dev/arandom) is not within the allowed path(s)

--> check "!ini_get('open_basedir')" before "is_readable()" ?

**Comment by paragonie-scott** [comment]
:+1:

**Comment by paragonie-scott** [comment]
Did https://github.com/paragonie/random_compat/commit/492528194aa2ed1ab13b5746a285551c7ad8b10a fix this error?

**Comment by paragonie-scott** [comment]
I've added a unit test to set open_basedir and it doesn't trigger an error: https://github.com/paragonie/random_compat/commit/7890f135803458c92a2ffc26d737f23458fc4526
