### ISSUE TITLE
php7 Compatibility problem

### ISSUE THREAD

**Issue by oasfuyou** [paragonie/random_compat#151]
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

58 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 58 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 58 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2

**Comment by paragonie-scott** [comment]
That's weird. That code shouldn't even be running in PHP 7.1 environments.

**Comment by narfbg** [comment]
It's not ... The guy just ran a static analyzer on a bunch of popular frameworks & libraries and reported everything that came out.

**Comment by paragonie-scott** [comment]
Ah, okay. I'm going to close this as a false positive. Thanks @narfbg
