### ISSUE TITLE
I think your packagist account has been hacked... 

### ISSUE THREAD

**Issue by adrianbsb** [paragonie/random_compat#157]
Unless I am missing something, but this looks weird. v9.9.99
https://packagist.org/packages/paragonie/random_compat

![screen shot 2018-10-26 at 10 59 36](https://user-images.githubusercontent.com/41574814/47552826-509c7300-d90e-11e8-806b-d37f3359403b.png)

**Comment by xabbuh** [comment]
Everything's alright here (see https://github.com/paragonie/random_compat/blob/master/README.md#version-99999). :)

**Comment by adrianbsb** [comment]
Thanks for the swift response, somehow I missed that line. I also took a look to the code and noticed there’s nothing wrong there. 
Probably this line should be added in higher up the page in the readme, so it’s easier to spot.
Thanks for this great library, and have a great day.

Regards,
Adrian.
