### ISSUE TITLE
Check for existence of mb_substr before mb_strlen usage

### ISSUE THREAD

**Issue by tsyr2ko** [paragonie/random_compat#16]
https://github.com/paragonie/random_compat/blob/master/lib/random.php#L301

```php
if (!function_exists('RandomCompat_strlen')) {
    if (function_exists('mb_substr')) { # <= just here
        /**
         * [striped comment]
         */
        function RandomCompat_strlen($binary_string)
        {
            if (!is_string($binary_string)) {
                throw new InvalidArgumentException(
                    'RandomCompat_strlen() expects a string'
                );
            }
            return mb_strlen($binary_string, '8bit');
        }
    } else {
        // portion not necessary
    }
}
```

It's about RandomCompat_strlen ... just below the line 301, you only use mb_strlen, so, just a copy/paste error about the function_exists on mb_substr :)

My 2 cents

**Comment by oittaa** [comment]
Actually if the test fails on line 301, we define function `RandomCompat_strlen()` differently starting from [line 331](https://github.com/paragonie/random_compat/blob/master/lib/random.php#L331). Only `strlen()` is used there.

**Comment by paragonie-scott** [comment]
The original code was one function definition with a static variable that cached an `if (function_exists())` check, but I decided to optimize it in a manner similar to how @lt suggested optimizing `random_bytes()` by checking only once.

https://github.com/paragonie/random_compat/commit/97ee310b41c2410f65922cf6a1b3d21510acd8f0#diff-3389ff8e306f9430cb1a83d3ef20c131

That's the commit that changed the strategy to the way it is now.

**Comment by oittaa** [comment]
Oh, now I get what @tsyr2ko meant. I was blind. We are testing `mb_substr()` even though `mb_strlen()` is used in the function.


Line 301 should be change from:
```
    if (function_exists('mb_substr')) {
```
to
```
    if (function_exists('mb_strlen')) {
```

**Comment by paragonie-scott** [comment]
Oh, oops! This is a benign mistake (if one exists, the other will too), but I'll correct it immediately.

Good catch @tsyr2ko :+1:

**Comment by tsyr2ko** [comment]
You're welcome, not important mistake as it's very rare that ```mb_substr``` was installed without ```mb_strlen```
