### ISSUE TITLE
Fortify scan Path Manipulation

### ISSUE THREAD

**Issue by Rohit272** [paragonie/random_compat#161]
Hi,
We are using paragonie/random_compat with laravel, on running the Fortify scan tool, i get the following error at:
paragonie/random_compat/other/build_phar.php, line 35

file_get_contents method is creating path manipulation error.
Is there any workaround or fix that can be applied here. Could this be taken care in the future versions .

Thanks.

**Comment by PatrickRose** [comment]
I don't think you need to worry about that file, it's only used if you're building a phar file which you shouldn't be doing as a consumer.

**Comment by paragonie-security** [comment]
@PatrickRose is 100% correct. We're an open source company and that means publishing the tools we use to bundle software with said software.
