### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by shital7mahajan** [paragonie/random_compat#162]
Hi,

I have run following PHPCS command and getting following error & warning:

`$ phpcs --standard=PHPCompatibility --extensions=php,module,inc,install,test,profile,theme --runtime-set testVersion 7.2 .`

FILE:  paragonie\random_compat\lib\byte_safe_strings.php
----------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES

 32 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 86 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

FILE: paragonie\random_compat\lib\random_bytes_mcrypt.php
----------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE

 58 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 58 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 58 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2

Any plan to resolve this?

**Comment by PatrickRose** [comment]
Why are you using a PHP7 polyfill when you're running PHP 7.2?

**Comment by glensc** [comment]
@shital7mahajan read phpcompatibility readme how to handle polyfills. no issue/bug in this project.

@PatrickRose likely the dependency comes from external project dependency, i.e using Symfony older branch whose minimum requirement is 5.6 for example.

**Comment by paragonie-scott** [comment]
Honestly, it shouldn't matter. PHPCS shouldn't be run on Composer dependencies.
