### ISSUE TITLE
CAPICOM implementation does not work (fix)

### ISSUE THREAD

**Issue by anzz1** [paragonie/random_compat#175]
Problem: ``method_exists`` does not work for the COM class.  
Tested non-working on Windows 7 x64, PHP5.6.32 (VC11-x86-ts) and PHP 7.3.33 (VC15-x86-nts)

Solution: Use ``is_callable`` instead.
```php
      $util = new COM('CAPICOM.Utilities.1');
      $method = array($util, 'GetRandom');
      if (is_callable($method)) { ...
```
See this gist for implementation example: https://gist.github.com/anzz1/29a787fac8ef6d693b41779911287505

Here is the [Microsoft CAPICOM 2.1.0.2 SDK](https://github.com/anzz1/capicom_sdk) if someone needs it.  
While kinda obscure in 2022, it's still an easy way for to add crypto capability for Windows PHP if for some reason you can't upgrade PHP itself.

**Comment by paragonie-security** [comment]
Thank you for reporting this. The COM approach is definitely the coldest path for random_compat users, but we're happy to fix this.
