### ISSUE TITLE
Update readme to indicate PHP 5.3.0+ is required

### ISSUE THREAD

**Issue by scottchiefbaker** [paragonie/random_compat#2]
The readme states:

```
PHP 5.x polyfill for random_bytes() and random_int() created and...
```

But the whole thing is wrapped in a `namespace` which requires PHP 5.3.0+

**Comment by paragonie-scott** [comment]
Good point! We encourage people to [run at least 5.4 as of July 7, 2015](http://php.net/eol.php), but this is worth noting. :+1:

**Comment by scottchiefbaker** [comment]
As far as I can see the `namespace` is the only thing not compatible with PHP 5.x though. Wouldn't be hard to work around it for older versions, but that may be more work than it's worth.

**Comment by paragonie-scott** [comment]
I can just make it a uniquely named function, if need be. We already test for its existence.

**Comment by scottchiefbaker** [comment]
Perfect! 

I believe there **was** a reason @nikic wrapped his `password_hash()` compat library in a namespace, but I don't remember what it was. Something to do with unit testing with PHPUnit maybe?

**Comment by ircmaxell** [comment]
There were a few helper functions that I needed, so I wrapped those in a namespace. And to keep it a single file, that meant putting an empty namespace around password_hash()...
