### ISSUE TITLE
Should we buffer freads?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#20]
Should we disable buffering completely or would it be worthwhile to set the read buffer to some sane default value (i.e. 32 bytes instead of PHP's default 8192 bytes)?

**Comment by redragonx** [comment]
Have you tested if it was any slower disabling buffering? I would make it so programmers can easily enable it as an option with the default value we pick such like 32 bytes. A global boolean with a comment with any warnings associated with buffering. 

Just an idea...

**Comment by paragonie-scott** [comment]
```php
<?php
define('RANDOM_COMPAT_READ_BUFFER', 0);
require 'vendor/autoload.php';

$start = microtime(true);
for ($i = 0; $i < 300000; ++$i) {
        $buf = random_bytes(32);
}
$end = microtime(true);
echo ($end - $start), "\n";
```
Averages:

     0 => 2.185293 s
     8 => 1.851262 s
    16 => 1.854915 s
    24 => 1.861923 s
    32 => 1.851915 s
    64 => 1.835347 s

To calculate these values, I ran each benchmark 10 times and took an average and rounded it to 7 decimal places. It looks like `0` is suboptimal and the difference among the non-zero values is not significant. If we change the `random_bytes()` invocation to only request 1 byte (typical for `random_int()`), this discrepancy evaporates.

I'm not sure what the optimal value is for read-buffering. 8 bytes is a conservative enough value (wastes less entropy) and still gets a performance gain.

cc @ircmaxell

**Comment by voku** [comment]
Does "stream_set_chunk_size()" the same as "stream_set_read_buffer()" ? | http://php.net/manual/de/function.stream-set-chunk-size.php

**Comment by redragonx** [comment]
8 bytes seem okay to me! 

@voku I don't think so.

**Comment by paragonie-scott** [comment]
@voku I'd have to delve into the C source code to see if it does the same thing, but `stream_set_read_buffer()` does exactly what we want.

I've set it to 8 bytes and I'm closing this issue. Feel free to open one if buffering becomes a problem.
