### ISSUE TITLE
Split implementation into separate files

### ISSUE THREAD

**Issue by narfbg** [paragonie/random_compat#23]
The all-in-one file approach is a necessity if all the environment dependencies are detected dynamically *within one function*, as it was originally. But since that has changed, I think using includes would (at least) make the code easier to follow.  
I for one got kind of lost for a moment between all the conditional declarations of the same function, so I'd suggest the following:

byte_safe_strings.php
random_bytes_com_dotnet.php
random_bytes_dev_urandom.php
random_bytes_mcrypt.php
random_bytes_openssl.php
random_int.php

... you know what to do with them. :)

**Comment by paragonie-scott** [comment]
:+1: Yeah, this will also make it easier to test each specific implementation.
