### ISSUE TITLE
fclose() for "random_bytes_dev_urandom.php" ?

### ISSUE THREAD

**Issue by voku** [paragonie/random_compat#25]
For now we only use fclose() if the check with fstat() fails, is there a reason why we don't use it before returning the value?

**Comment by narfbg** [comment]
Yes, the file descriptor is cached for repeated usage.

**Comment by narfbg** [comment]
But that brings up an interesting point ...

If #22 tries to avoid a race condition where /dev/urandom is altered mid-runtime, does caching any make any sense? @jedisct1

**Comment by paragonie-scott** [comment]
The reason we `fclose()` it when `fstat()` fails is to make sure `fread()` fails closed.

As far as I'm aware, caching the file descriptor is mainly for performance reasons. Does @lt have any other insights to add?

**Comment by narfbg** [comment]
Performance reasons was why I questioned #22 in the first place, but my question here was: if `fstat()` negates the caching performance gain, yet is really necessary, then why bother caching in the first place.

But I did some thinking and I don't think it's possible for /dev/urandom to be re-mounted without the file pointer failing, so there should still be a performance gain (and safety preserved).

**Comment by paragonie-scott** [comment]
You're right, I can't think of the kernel allowing it to be unmounted without the file pointer being closed.

Is this safe to close?

**Comment by narfbg** [comment]
Yep, should be closed.
