### ISSUE TITLE
random_int() isn't outputting appropriate values

### ISSUE THREAD

**Issue by scottchiefbaker** [paragonie/random_compat#3]
I ran the following code on my PHP 5.6.x installation:

```
require('random.php');

for ($i = 0; $i < 10; $i++) {
    $a = random_int(0,100);

    print "$a ";
}
```

And got the following output `1 6 5 4 3 4 1 3 6 4`. Repeated iterations always output integers between 0 and 8 even though the specified maximum was 100.

**Comment by scottchiefbaker** [comment]
Also, setting the min to 0 and max to 999 gives me output between 1 and 99.

**Comment by paragonie-scott** [comment]
Okay, please pull master and tell me if it's behaving correctly.

**Comment by scottchiefbaker** [comment]
Output appears more appropriate now. The distribution of random numbers is similar to `mt_rand()` now. This is much better.

**Comment by paragonie-scott** [comment]
Yep, here's the patch that fixed it: https://github.com/paragonie/random_compat/compare/93be154a140ee720c35c381a33ac2a5bb9b58bab...87f8cdb816cdbcc885f2c7543b5b637e360e31a9

**Comment by scottchiefbaker** [comment]
I wonder if the unit tests shouldn't be updated to catch this? Generating a pool of random numbers should generate about 62% coverage of the given range.

We could generate 1000 random numbers and make sure that the coverage is between 60% and 70%?

**Comment by paragonie-scott** [comment]
Like so? https://github.com/paragonie/random_compat/commit/ea48c268ef4339122df05d6afc7ae3eeb3255a20

(I used a wider range because it failed randomly in my VM. 58% coverage, 73% coverage, usually 60-70 though.)

**Comment by scottchiefbaker** [comment]
Yes this looks good. 

We might also want to modify the unit tests to check for the min/max output being the near the outer edges of the given range. In the above bug, we were only output values 0 - 80. If we were testing that we had a value in the lowest 2%, and the highest 2% we would catch that.

I'll open a separate "issue" on that, since this is already closed.
