### ISSUE TITLE
Consider Scrutinizer Integration

### ISSUE THREAD

**Issue by chriscct7** [paragonie/random_compat#33]
Scrutinizer is a great free (for Open Source projects) tool that can identify static code issues (security, docblocks, etc), have an extra run at your unit tests, and indentify areas where code could be improved (to reduce complexity or increase documentation), as well as areas the current unit testing suite doesn't actually cover (which on a related note you should consider having PHPUnit take a few extra seconds and generate a clover report https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/.travis.yml#L33)

Adding it is as simple as tacking on a line to the end of your Travis file to send the Travis report to Scrutinizer, and adding a yml config file for it:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/.travis.yml#L35
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/.scrutinizer.yml

**Comment by paragonie-scott** [comment]
:+1: This is a good idea. Thanks for the suggestion. I'll look into setting this up as soon as I'm finished with what I'm currently working on.

**Comment by paragonie-scott** [comment]
Well, I added Scrutinizer, but it doesn't seem to like that we're conditionally re-defining the `random_bytes()` function (depending on the operating environment). I'm not sure if I'm missing a step or two to get a green button on the README.

**Comment by geggleto** [comment]
I went looking around their documentation ... Perhaps this would be some help @paragonie-scott 

https://scrutinizer-ci.com/docs/reviews/filtering_issues_and_false_positives

**Comment by rugk** [comment]
As Scrutinizer has been added, I think this issue can be closed.
