### ISSUE TITLE
Exception should be thrown on use

### ISSUE THREAD

**Issue by rchouinard** [paragonie/random_compat#35]
The behavior of the PHP7 `random_bytes()` and `random_int()` functions will change to throw `Exception` on use if there are any issues with the entropy source: https://wiki.php.net/rfc/random-function-exceptions

This compatibility library should probably be updated to behave similarly, rather than throwing on load where it's arguably harder to handle.

**Comment by paragonie-scott** [comment]
The throwing on load only occurs if there is literally no way to proceed.

This means if:

1. You're running PHP < 5.3
2. You don't have ext/mcrypt enabled
3. You're running Linux in a jail (no /dev/urandom access)

Then there's literally no way to generate random bytes. The PHP extension can work around this via the `getrandom(2)` syscall, but we can't access syscalls from PHP.

**Comment by paragonie-scott** [comment]
However, there is no harm in deferring this until the first time random_bytes() is invoked.

https://github.com/paragonie/random_compat/commit/4f39309880a98da70c9f3840e7a1d8e21d36afaa

**Comment by rchouinard** [comment]
The why always made sense to me, the when did not. Looks like your commit and v1.0.1 tag now throws on call, which makes much more sense, I think.

Thanks for your efforts!

**Comment by paragonie-scott** [comment]
Agreed. Thanks for pointing out a better way to do things. :+1:
