### ISSUE TITLE
Relax open_basedir restriction

### ISSUE THREAD

**Issue by notr1ch** [paragonie/random_compat#46]
The code at https://github.com/paragonie/random_compat/blob/master/lib/random.php#L55 tests if open_basedir is enabled and gives up trying /dev/urandom if it is. However, if open_basedir is set to allow access to /dev/ then the opportunity to use /dev/urandom is lost.

Consider removing this check and relying on is_readable (prefixed with @ if you're worried about open_basedir warnings).

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/4629665f403924470bfe51027f4e6f80ea62db9e

Sort of like this?

**Comment by notr1ch** [comment]
Yep! That's exactly what I had in mind.

**Comment by paragonie-scott** [comment]
Excellent. It should be in 1.0.6 once it's ready to release. #50
