### ISSUE TITLE
Attacker can write to /dev/urandom on Windows; subsequent reads get non-random data

### ISSUE THREAD

**Issue by cweagans** [paragonie/random_compat#49]
See https://www.drupal.org/node/2550519#comment-10442967 for the concern. Is this something that you'd be interested in mitigating in random_compat?

**Comment by paragonie-scott** [comment]
See the latest comments in #5 -- if we drop support for old OpenSSL we'll have to tag that as a 1.1.0 branch because of BC concerns.

**Comment by cweagans** [comment]
Actually, this doesn't have anything to do with OpenSSL.

The idea is that if some process manages to write a file to `/dev/urandom` on Windows, anything that's trying to read `/dev/urandom` will get a decidedly non-random value (i.e. just the contents of the file).

**Comment by tom--** [comment]
> /dev/urandom on Windows

?

**Comment by cweagans** [comment]
Yes, I know it doesn't exist. If you try to *write* a file to `/dev/urandom`, it's presumably saved somewhere, right? I'm really not sure, to be honest. It's been a long, *long* time since I've done anything on a Windows box. Followed up on the d.o issue for clarification: https://www.drupal.org/node/2550519#comment-10443329

**Comment by tom--** [comment]
I get it. On Windows, an attacker could write a file to "C:\dev\urandom" and an unwitting PHP script might read that when reading from path `"/dev/random"` and not know that it's bogus.

I have to try this out right away. It's a terrifying idea.

**Comment by cweagans** [comment]
Right. It seems like PHP should complain loudly about that, but then again, there's a lot of things PHP should do that it doesn't (and vice versa).

**Comment by tom--** [comment]
https://gist.github.com/tom--/556f475c44516d296270

**Comment by cweagans** [comment]
omfg.

**Comment by paragonie-scott** [comment]
Right. This won't work on random_compat because [we have sanity checks already](https://github.com/paragonie/random_compat/blob/master/lib/random_bytes_dev_urandom.php#L60-L63).

But excluding Windows from ever attempting `/dev/urandom` hurts nothing: https://github.com/paragonie/random_compat/commit/f56c3e7cf10c5860f69ef67c24d84fc8508c2140

**Comment by narfbg** [comment]
This has never been a problem for random_compat - I know because I was looking for it while initially reviewing the code and would've alerted about it.

**Comment by tom--** [comment]
I'm very glad to hear that.

What's terrifying is for years we've been telling people "use dev urandom" without warning them about this hazard. This is a very easy thing to overlook.

**Comment by tom--** [comment]
@cweagans I produced an infographic. Perhaps you'd like to share it on that Drupal issue.

![dev random on Windows](https://d1ro8r1rbfn3jf.cloudfront.net/ms_79026/2I3drXVe84l8rij0OhgYJH33bL5dkE/Win7%2B%255BRunning%255D%2B2015-10-13%2B12-29-18.png?Expires=1444849657&Signature=GAX7bHx2W-MRgaM8HEC33HIhI9yFIHudIpcGCd3t5XpVFgx8ejAPrJ6QPabbp-lONpl~htVcLta3~GTiy60PhWLoC6JNh6KITX~s5Jv-JAaq1cOsUCGUoG1ZTYrrq7J6vusEhmE6yipQd3sLXyImAxbnNubSoS6LVEwz9rsfybBlVuZ8tl4cEjsCo6H29NTeO3BA0bOQRn47jIlZZVjk0L2rgkomqsADxN2-g4pDVMtdyl-WpvoxdJtwd5hxL0A5RV7VB9o~Cvz43RZDLs0h5OLswspmX4To~dJifqhEfHs7ThxDmxBbCBJEKvXlPQiJdtlbX40R~nYbB1iIpWluLg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by paragonie-scott** [comment]
Do the added checks, plus the ones that we arleady had in place, solve this issue?

**Comment by tom--** [comment]
@paragonie-scott I think so.
