### ISSUE TITLE
Version 1.1.0 Roadmap

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#51]
1. Expunge OpenSSL. This should only affect people with weird set-ups.

Does anything else need to change?

**Comment by ircmaxell** [comment]
Suggest not removing OpenSSL, but instead making it a last-resort fallback.

**Comment by paragonie-scott** [comment]
For the record, that's what [we currently do](https://github.com/paragonie/random_compat/blob/1c29dbb09f0ab8c04f332402b27276cd87739abe/lib/random.php#L77-L91).

**Comment by geggleto** [comment]
I guess the question really is, is some insecurity acceptable in your application. Given that this is suppose to enhance security as an app developer I would much prefer an error instead of a less than ideal security package.

**Comment by ircmaxell** [comment]
If you want to prevent usage on misconfigured servers, don't provide the library at all (since anything can be faked or misconfigured).

Heck, I can write:

    function mcrypt_create_iv($size) {
        return str_repeat(4, $size);
    }

There is only so much you can do to protect people from themselves. I'd suggest leaving OpenSSL in place and simply documenting the concerns.

**Comment by paragonie-scott** [comment]
I'm inclined to agree. Most platforms won't depend on OpenSSL since it's already the last resort.

**Comment by SamMousa** [comment]
> If you want to prevent usage on misconfigured servers, don't provide the library at all (since anything can be faked or misconfigured).
> 
> Heck, I can write:
> 
> function mcrypt_create_iv($size) {
>     return str_repeat(4, $size);
> }
> There is only so much you can do to protect people from themselves. I'd suggest leaving OpenSSL in place and simply documenting the concerns.

There is a difference between being actively mislead and just having a bad setup though, right? We can do very little if the attacker has the power to inject that code or alter the environment..
