### ISSUE TITLE
Comments on implementation.

### ISSUE THREAD

**Issue by lt** [paragonie/random_compat#6]
More of a list of comments than a specific issue.

Feeling uncertain about your fallback order.

For systems that have it `openssl_random_pseudo_bytes`  should be used first, it is both the quickest and well rounded provider of random. It uses it's own internal buffer/pool which draws multiple sources making it faster than direct file based random, but also draws from OS appropriate sources on windows.

Before 5.5.26 and 5.6.10 [`mcrypt_create_iv` did not use file descriptor caching](https://github.com/php/php-src/pull/1201) which makes it very slow for repeated use.

For random heavy applications, speed order for the majority of installations, openssl > /dev/*random > mcrypt. Can't comment on CAPICOM.

You might want to implement fd caching yourself. Opening and closing handles is pretty intensive work.
``` PHP
function random_bytes()
{
    static $fd;
    if (!$fd) {
        $fd = fopen(...
```

I'd say check for arandom, but on systems I care about, urandom is an alias of arandom anyway ;)

Consider moving the checks for supported implementations outside of the function? It seems wasteful to have to cascade through all of the existence checks on every call.

``` PHP
if (!function_exists('random_bytes')) {
    if (...) {
        function random_bytes($bytes) {
        ...
    } elseif ( ...) {
        function random_bytes($bytes) {
        ...
````

**Comment by paragonie-scott** [comment]
> For systems that have it `openssl_random_pseudo_bytes`  should be used first, it is both the quickest and well rounded provider of random.

Originally that's how that function was written, but after the discussion in #5, I demoted it to being the last resort.

I'm hesitant to promote a possibly-insecure function over a definitely secure function, even if it is more performant.

Can @MasonM @defuse @ircmaxell @padraicb @enygma @narfbg @GrahamCampbell and/or @jedisct1 weigh in and offer their opinion when they get a chance? I'd like to make sure that, if I revert my decision to demote `openssl_random_pseudo_bytes()`, it won't put anyone at risk.

> You might want to implement fd caching yourself. Opening and closing handles is pretty intensive work.

Will do. Thank you for the suggestion! :+1:

> Consider moving the checks for supported implementations outside of the function? It seems wasteful to have to cascade through all of the existence checks on every call.

I was actually thinking about adding a cache for that very reason (see: [`PasswordCompat_strlen()`](https://github.com/paragonie/random_compat/blob/58a4993595db71a801a4d242c98cd82a7e7fad20/lib/random.php#L219-L230), but your idea makes a lot more sense. :+1:

**Comment by narfbg** [comment]
No opinion about the OpenSSL thing ... this is the first time I hear it might be insecure *and* set `$secure` to TRUE at the same time.

**Comment by oittaa** [comment]
How about consolidating arandom and urandom tests? Line 32 could be something like this:
```
    } elseif (is_readable($d = '/dev/arandom') || is_readable($d= '/dev/urandom')) {
```
and then use ```$d``` on line 45 instead of ```'/dev/arandom'```. The whole copy&paste urandom block could be removed.

**Comment by lt** [comment]
Checked out #5 - @MasonM you might want to comment.

Correct the OpenSSL docs deprecate `RAND_pseudo_bytes`, but I wondered what is the *actual* difference between pseudo and non-pseudo.

1. [`RAND_pseudo_bytes`](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/rand/rand_lib.c#L165) gets the [default rand method](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/rand/rand_lib.c#L107) which is going to be `RAND_SSLeay` unless you have an exotic setup

2. Pseudo or not [the same function is called with a final parameter to indicate "pseudo"](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/rand/md_rand.c#L605)

3. `pseudo` is only referenced once within this function, to [suppress an error message](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/rand/md_rand.c#L590). The function returns 1 or 0.

4. PHP only [checks for a negative return value](https://github.com/php/php-src/blob/c01943bffc8b719e552d307f522820d50f783a4c/ext/openssl/openssl.c#L5459). This can only happen if [there is no pseudo-random implementation, or the pseudo-random method is exotic](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/rand/rand_lib.c#L168)

5. [Other](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/engine/eng_rdrand.c#L64) [bundled](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_padlock.c#L779) [engines](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_aep.c#L695) [also](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_4758cca.c#L883) [behave](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_chil.c#L1089) [this](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_cswift.c#L215) [way](https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/engines/e_sureware.c#L645) - Basically, the only way to get a negative return and for PHP to cry about weak crypto is if the pseudorandom function isn't implemented, and you get NO bytes at all from OpenSSL.

Have I gone mad? Someone please double check because this is just a lunchtime scan of code I'm unfamiliar with.

**Comment by paragonie-scott** [comment]
No, you're quite sane. OpenSSL, however, is not.

Basically, we have three conditions:

* OpenSSL returns secure random data -> `$crypto_strong` is `true`
* OpenSSL returns data before it's seeded -> `$crypto_strong` is `true`
* OpenSSL returns no data -> `$crypto_strong` is `false`

At this point, I'm unsure if we should even *trust* openssl to return CS data or just throw an exception if neither mcrypt, arandom/urandom, or CAPICOM succeed. Saving grace: If this is run on OpenBSD, PHP will be compiled against libressl, which uses `arc4random_buf()`.

**Comment by lt** [comment]
We're straying quite far from a userland replica, but, I think this is a potential solution.

1. If the platform has /dev/*random then we use it first with fd caching
2. If the platform is windows, use OpenSSL (`openssl_random_pseudo_bytes` on Windows uses `CryptGenRandom` not `RAND_pseudo_bytes`)
3. Finally use mcrypt if available.

**Comment by SammyK** [comment]
:+1: for /dev/*random > mcrypt > OpenSSL

Just make sure to check for the `open_base_dir` ini setting before checking for `/dev/*random` to [keep it from throwing errors when `open_base_dir` is set](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/PseudoRandomString/UrandomPseudoRandomStringGenerator.php#L43-L48). :)
