### ISSUE TITLE
On Windows, CAPICOM is deprecated

### ISSUE THREAD

**Issue by nicolas-grekas** [paragonie/random_compat#67]
I don't know if it's possible (I didn't managed yet), but since CAPICOM is deprecated since Vista, using `$rng = new DOTNET('mscorlib', 'System.Security.Cryptography.RNGCryptoServiceProvider');` would be preferable.

**Comment by paragonie-scott** [comment]
So the rumors of CAPICOM's demise were not greatly exaggerated after all! Good to know.

I'll work on this immediately.

**Comment by paragonie-scott** [comment]
http://stackoverflow.com/questions/6497670/calling-rngcrypto-from-coms-dotnet-class-from-php

Well, this seems to be a non-starter.

**Comment by nicolas-grekas** [comment]
I tested the same and some more variants this morning without success...
For ref, here is what wikipedia says about CAPICOM: https://en.wikipedia.org/wiki/CAPICOM
> CAPICOM was not included in Windows 7

**Comment by paragonie-scott** [comment]
Right. How can we invoke `$rng`? It seems to expect a `Variant`, but I've yet to get this to work.

**Comment by paragonie-scott** [comment]
http://news.php.net/php.internals/88882
http://news.php.net/php.internals/88883

Looks like DOTNET is a non-starter.

**Comment by paragonie-scott** [comment]
Although CAPICOM is indeed deprecated, I cannot get DOTNET's API to work in PHP. I don't think we can resolve this.
