### ISSUE TITLE
OpenSSL on Windows: Require PHP 5.4.1?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#73]
`openssl_random_pseudo_bytes()` on Windows has been doing the correct thing since 5.4.1. One WordPress user has reported that it [hangs even on PHP 5.3.5](https://core.trac.wordpress.org/ticket/34409).

There are two ways to remedy this:

1. Release a version 1.1.0 that kills OpenSSL, like @tom-- had suggested.
2. Require 5.4.1 for this fallback to work.

Alternatively, we're going to be flooded with complaints about it making peoples' WordPress blogs slow/unresponsive when WP4.4 drops.

**Comment by narfbg** [comment]
Can we investigate the conditions under which `openssl_random_pseudo_bytes()` can block? I'm thinking it may depend on the OpenSSL and/or Windows version numbers.

**Comment by paragonie-scott** [comment]
Certainly! If it turns out to be, e.g., a < 5.3.7 on Windows issue, we can just bump the 4 to a 7.

If random_compat fails, WP will fall back to what it did before, but for most users (i.e. they don't run outdated PHP on a Windows server), they should get our CSPRNG.

**Comment by narfbg** [comment]
Actually, I was saying it may not be tied to a specific set of PHP versions on Windows.

We're obviously talking about pre-5.4 on Windows, but beyond that, couldn't it be limited to Windows XP for example? Or maybe you wouldn't be affected as long as you have OpenSSL 1.0+?
Or for all Windows versions, but only as the effect of a limited-access user account? Not that I see how we could detect this one in particular, but still ... :)

**Comment by dd32** [comment]
FWIW as it's worth mentioning directly here, `openssl_random_pseudo_bytes()` (in PHP) is short-circuited [to use the WindowsCrypto API](https://github.com/php/php-src/commit/5fb257074253f2439ddeb6d789bfca39d4937a9e) in PHP 5.4.1+.

My understanding is that
 * it shouldn't even be tried on Windows in < PHP 5.3.4 (Blocking)
 * probably shouldn't be used on windows in < PHP 5.4.1 depending on the SAPI type (potentially slow on single-request CGI, but mod_php may be fine as it'll build up a buffer of random data)
 * and is probably fine on all versions of linux.

At least in WordPress I'll probably bump it to a 5.4.1 requirement if there's any reports of breakage in 5.3.4~5.4.1, although I've not actually tested it.

**Comment by dd32** [comment]
@paragonie-scott I don't suppose you've had a chance to look into this closer at all?

**Comment by paragonie-scott** [comment]
Sorry, one of my projects is in crunch time right now, so I haven't had time to investigate this. If anyone can test PHP 5.3.x (for 3 >= x >= 7) or PHP 5.4.0 on Windows, please do.

**Comment by paragonie-scott** [comment]
https://docs.google.com/spreadsheets/d/1sbHSUhGSZghMeRNIzSQ1YLhGh9BKP1ZMspK4OGslDyI/edit?usp=sharing

**Comment by paragonie-scott** [comment]
Made a mistake. Now it's editable.

**Comment by dd32** [comment]
FWIW It varies between SAPI method too, CLI (in a windows shell) doesn't appear to have a problem, but mod_php does, I didn't test per-request CGI. (I was testing with XAMPP under Windows XP in a VM)

In that testing, CLI was ~0.002s/request, while mod_php was 1.2s/request.

In [WordPress I've switched it to be PHP 5.4.1+ to be safe](https://core.trac.wordpress.org/ticket/34409#comment:11), it's clear to me that older versions may not be reliable from the code and we're not willing to risk it, mcrypt and/or dotnet appears to often be available in the WAMP/XAMPP builds i've tried.

**Comment by paragonie-scott** [comment]
We haven't heard much from Windows users. I might end up making the same change since we *know* a performance bug [was fixed in 5.4.1](https://github.com/php/php-src/commit/5fb257074253f2439ddeb6d789bfca39d4937a9e#diff-69bad938d17f4283faa5f7fea17fa627).

**Comment by paragonie-scott** [comment]
19f765b66c6fbb56ee3b11bc16d52e38eebdc295 Yeah, I might as well make this a uniform change.

**Comment by narfbg** [comment]
Most likely unrelated, but mentioning mod_php vs CLI reminded me of this: http://stackoverflow.com/questions/31629754/mcrypt-create-iv-stalls-but-only-through-apache
