### ISSUE TITLE
Please prefer anything before mcrypt

### ISSUE THREAD

**Issue by remicollet** [paragonie/random_compat#77]
libmcrypt is a dead cow, relying on it for anything related to cryptographics is a terrible mistake.

Read: http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt

And yes, I will fight as much as I can to see this extension die and be moved from PHP to pecl

**Comment by paragonie-scott** [comment]
Hi remi

I agree with you 99%.

* mcrypt_create_iv isn't part of libmcrypt, it's part of ext/mcrypt
* openssl is actually worse here

But seriously, mcrypt needs to be retired. If you want to RFC that for 7.1 it has my support

**Comment by remicollet** [comment]
> But seriously, mcrypt needs to be retired. If you want to RFC that for 7.1 it has my support

RFC have not pass for 7.0 :(
So will open a RFC soon to mark it as deprecated in 7.1... and removed in 8.0

Chicken and egg issue... people use it because available, and don't want to remove it because used...

**Comment by jedisct1** [comment]
![Kill it](http://img2.wikia.nocookie.net/__cb20131124034846/walkingdead/images/1/1e/Eve-myles-kill-it-eccbc87e4b5ce2fe28308fd9f2a7baf3-206_(2).gif)

**Comment by paragonie-scott** [comment]
> Chicken and egg issue... people use it because available, and don't want to remove it because used...

I can commiserate with you on feeling frustrated there. I've been telling people not to use mcrypt where possible too. To further this cause, I rewrote a big chunk of [Defuse's library](https://github.com/defuse/php-encryption) to use OpenSSL instead of mcrypt.

I'm also trying to get [libsodium](https://github.com/jedisct1/libsodium-php) as a core PHP extension (i.e. doesn't need PECL) in 7.1, so we're not *only* taking something away, but giving PHP developers something far better.

**Comment by adamel** [comment]
@paragonie-scott, why do you say that openssl is worse than mcrypt?

**Comment by paragonie-scott** [comment]
https://core.trac.wordpress.org/ticket/34409

**Comment by adamel** [comment]
Ah, that sounds bad, but also is very Windows-specific, so I guess openssl only needs to be avoided if running on Windows **and** PHP is older than 5.4.1?

**Comment by paragonie-scott** [comment]
@remicollet Do you still feel strongly about this issue? We've documented our reason for the current order in [ERRATA.md](https://github.com/paragonie/random_compat/blob/master/ERRATA.md).

**Comment by remicollet** [comment]
I understand the explanation about the function being part of the mcrypt extension, not of libmcrypt library.

Despite, anything which create grip to mcrypt extension is IMHO bad.

**Comment by paragonie-scott** [comment]
Well, this library is a NOP in PHP 7. :)

**Comment by paragonie-scott** [comment]
@remicollet I'm going to close this and continue to push for mcrypt to be deprecated with PHP Internals. :)
