### ISSUE TITLE
random_bytes_dev_urandom has unusable performance on php 5.6

### ISSUE THREAD

**Issue by adamel** [paragonie/random_compat#78]
Due to stream_set_read_buffer() not doing what one would think it does, the first call to random_bytes()
in random_bytes_dev_urandom.php will *always* read 8 KiB data from /dev/urandom.

Unlike what http://php.net/manual/en/function.stream-set-read-buffer.php describes, the $buffer argument in php 5.6 is actually treated as a boolean flag - if it is zero the stream is unbuffered, if it is non-zero the stream is buffered, but the buffer size is never changed in any way...

Realized this after benchmarking a lumen app and seeing that the majority of CPU time was actually spent in the kernel generating random data.

**Comment by narfbg** [comment]
In my projects I've been using `stream_set_chunk_size()` instead.

Not sure if it actually behaves differently, but if it does - I'm guessing `stream_set_read_buffer()` could be setting the size to store in memory, while `stream_set_chunk_size()` would set the size to actually read.

**Comment by adamel** [comment]
It should also be noted that the `openssl_random_pseudo_bytes()` function in PHP no longer (as of PHP 5.6.10, see https://bugs.php.net/bug.php?id=70014 ) uses
the deprecated `RAND_pseudo_bytes()` function, but the supported `RAND_bytes()`, so IMHO using the `random_bytes_openssl.php` implementation should now be preferred before reading directly from `/dev/urandom`.

**Comment by adamel** [comment]
It should also be noted that `RAND_pseudo_bytes()` in OpenSSL actually calls `RAND_bytes()`. The only difference is that `RAND_bytes()` considers it an error if the random generator is not sufficiently seeded, while `RAND_pseudo_bytes()` just indicate that case by returning zero.

As `random_bytes_openssl.php` actually throws an error when the `$crypto_strong` bool is false it is 100% safe to use the PHP openssl extension in all PHP versions, including the ones using `RAND_pseudo_bytes()`.

**Comment by narfbg** [comment]
Surely these last two comments are more relevant to issue #77 than `stream_set_read_buffer()`?

**Comment by adamel** [comment]
That issue is about preferring everything before mcrypt. The point of my last two comments here is that openssl should be preferred before dev_urandom, which is not the same thing.

**Comment by paragonie-scott** [comment]
OpenSSL should be the last choice for two reasons:

1. It is a userspace PRNG that may or may not be CS. I certainly don't trust it more than `/dev/urandom`.
2. In previous versions of PHP, it used `RAND_pseudo_bytes` which means it would have failed silently if invoked before being seeded.

Also, @ircmaxell was investigating claims that `openssl_random_pseudo_bytes()` created duplicate UUIDs (version 4), and I'm hesitant to promote the use of openssl above `/dev/urandom` (which is reliably secure on Linux).

On topic: Please tell me if `stream_set_chunk_size()` fixes this problem.

**Comment by paragonie-scott** [comment]
By failed silently, I mean returned weak pseudorandom data that's easily guessable. (This level of failure would be Debian weak key level bad.)

**Comment by adamel** [comment]
`stream_set_chunk_size()` makes things better when requesting small blocks but not really good if requesting larger blocks (assuming the same size of 8 as used by the default `stream_set_read_buffer()` call). If calling `random_bytes(25)` PHP will then actually do four `read()` syscalls of 8 bytes each...

**Comment by paragonie-scott** [comment]
How much of a performance degradation would this actually incur? Have you benchmarked the difference, and is it significant enough to be a serious problem?

**Comment by adamel** [comment]
Linux seems to spend enough time actually generating random data that the syscall overhead of doing 8 byte `read()s` is neglectable regardless of how much random data the application need, so `stream_set_chunk_size()` seems like a good fix there. Other platforms having /dev/urandom might behave differently of course.

Always reading 8k data on the first read as in the current code on the other hand had a noticable impact. I can check the numbers for that tomorrow if you like.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/a208865a5aeffc2dbbef2a5b3409887272d93f32

This adds an `stream_set_chunk_size()` invocation on the first run. Hopefully that solves the 8192-bytes-from-urandom problem.

**Comment by adamel** [comment]
Yes, that should work fine.
