### ISSUE TITLE
random_int() gives incorrect output, if the answer should be a negative number

### ISSUE THREAD

**Issue by oittaa** [paragonie/random_compat#8]
For example
```
echo random_int(-100, -10);
9223372036854775774
```
Added this debug code just before returning the answer:
```
echo "DEBUG: got ".(int) ($min + $val)."\n";
        return (int) ($min + $val) & PHP_INT_MAX;
```
and this is what it gave:
```
DEBUG: got -34
```

Seems like `& PHP_INT_MAX` isn't the correct solution here.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/41c27706b0685bfe36c7fa369edd937e4adb2e68#diff-3389ff8e306f9430cb1a83d3ef20c131L207

I found and fixed this a few minutes ago. Good catch, however! :+1:

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/35359ae3451e7ecfbac4c5bf2afa1a83ba457a2d this ought to prevent this from ever reoccurring in a regression.

Thanks again for taking the time to review and test our library. :+1:

**Comment by oittaa** [comment]
Just heads up that there's a typo in the test. The last index should be 3, not 2.
