### ISSUE TITLE
documentation on setup

### ISSUE THREAD

**Issue by My1** [paragonie/random_compat#80]
okay after trying out a lot I figured out how to install and use this.
I wanted just the random_int so I tried that one which didnt go nice since there was stuff from the other files that was needed so it would be nice to write at least a single sentence about that you need to copy all the files from /lib into ine folder and include/require the random.php which will make it work.

**Comment by GrahamCampbell** [comment]
Just install it with composer. Done

**Comment by GrahamCampbell** [comment]
```
composer require paragonie/random_compat
```

That's literally the entire installation process done.

**Comment by GrahamCampbell** [comment]
I wouldn't recommend trying to copy the files into your code.

**Comment by My1** [comment]
so in short what is composer? I never used it and I dont think I have that one on a normal shared hosting.

**Comment by paragonie-scott** [comment]
> I wanted just the random_int 

`random_int()` depends on `random_bytes()`. If you can't use composer or a git submodule, grab the .tar.gz for 1.1.4 and upload somewhere, and include `lib/random.php`. You'll get both functions.

**Comment by GrahamCampbell** [comment]
NB, Looking at the composer.json is a good idea even if you really don't want to use composer for whatever reason. In particular: https://github.com/paragonie/random_compat/blob/master/composer.json#L32.

**Comment by redragonx** [comment]
You should look into composer before dismissing it. Don't be afraid to use new technology, what's the point of developing software if devs never want to change? Makes no sense to me.

**Comment by My1** [comment]
I am not dismissing it completely, but I know next to nothing about it and to top it off it's an alpha (so both security and stability are unclear) where the core file is about 65k lines of code. I dont wanna read over this and check whether it's okay... (as said in another place in here)
when it goes stable then I might check it out more.

@paragonie-scott you know I saw that when I looked into the fuction. didnt really know it before.

@GrahamCampbell well yeah I realized that later (as said in another place in here)

**Comment by redragonx** [comment]
Are you scared of security bugs on your dev machine?

**Comment by My1** [comment]
security and bugs. also I think if my "Dev Machine" is my everyday Laptop then yes. I dont see that much problems with this little library, it's just some small PHP and looks simple enough to understand it and for a PHP script to bring a server down, I am not so sure, especially when script runtime is limited to 30 sec.

**Comment by GrahamCampbell** [comment]
> Are you scared of security bugs on your dev machine?

I think the meaning here is that you can't properly deal with security issues without composer.

**Comment by My1** [comment]
yeah but I cannot deal with the issues of a 65k software that is in alpha that I didnt write.
I have enough issues with my PHP site whose core is about 1,4k lined plus all the pages that utilize it. I dont have time to get to the bugs of that composer.

**Comment by paragonie-scott** [comment]
I could build a phar if we need to cover the needs of "copy & paste programmers", like https://github.com/defuse/php-encryption/issues/94

**Comment by My1** [comment]
well it doesnt need to be one file or whatever, I can easily download a folder of files (github release system) and include one file. the point is to know what files are needed and what has to be included.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/pull/83

This should do the trick. If anyone would like to help test it out (replace the keypair with your own), please do. :)

**Comment by paragonie-scott** [comment]
1.1.6 adds instructions for Composer *and* manual installing. I'll continue to research the viability of Phar distribution for #83. For now, I believe this is resolved?

**Comment by My1** [comment]
this is pretty nice, providing instructions for both sides.
nothing to complain.
