### ISSUE TITLE
libSodium support broken?

### ISSUE THREAD

**Issue by dd32** [paragonie/random_compat#85]
It's been reported to WordPress Trac that the libSodium implementation is broken - https://core.trac.wordpress.org/ticket/35327

I'm hoping someone here will be able to confirm if that's the case. According to the libsodium documentation, it looks like it's being called *correctly*.

> *Usign libsodium for random bytes breaks plugin update in WP 4.4*
Running WP 4.4 on 
CentOS 7.2.1511
nginx 1.9.9
PHP 5.4.16
libsodium 1.0.5
php-pecl-libsodium 1.0.2
After updating to WP 4.4 plug-ins cannot be updated anymore.
Updates fail with 
[06-Jan-2016 12:21:21 UTC] PHP Fatal error: Call to undefined function Sodium\randombytes_buf() in /var/www/verifyne.me/wp/wp-includes/random_compat/random_bytes_libsodium.php on line 69
The lines 66 and 69 state
`\Sodium\randombytes_buf`
whereas the following works for me
`\Sodium::randombytes_buf`

**Comment by paragonie-scott** [comment]
> `\Sodium::randombytes_buf`

They're using an extremely outdated version of libsodium. They switched from a class to static methods to namespaced functions before 1.0.0 was tagged. 

Pre-1.0.1 has a bug with memzero(), caused by undefined behavior in how PHP handles strings, that would also cause data corrpution in PHP 7, so there's definitely a strong incentive to upgrade.

Ping @jedisct1 who can confirm/deny the details.

**Comment by paragonie-scott** [comment]
> libsodium 1.0.5
> php-pecl-libsodium 1.0.2

![wat-gigantic-duck](https://cloud.githubusercontent.com/assets/11591518/12143286/3a3f2bd6-b44d-11e5-8a5c-1a0e5cd7d85e.jpg)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/3f325770f5053292d03b4782fab2394efe18dbbc

This should work around the problem. I don't have a more reliable way of supporting both methods (i.e. not creating two files) without parse errors.

**Comment by dd32** [comment]
> I don't have a more reliable way of supporting both methods (i.e. not creating two files) without parse errors.

Unfortunate, but a fact of life.

I'm not sure what to make of the versions either, but if it's possible for it to happen, it certainly does somewhere.

Thanks for your quick turn around (as usual) @paragonie-scott

**Comment by paragonie-scott** [comment]
I'm gonna let this sit for ~24 hours to give folks a chance to tell me I made a mistake, and then I'll tag 1.1.5.

**Comment by narfbg** [comment]
I googled for php-pecl-libsodium RPMs a bit and it appears that there are some old Fedora packages with version 0.1.2/0.1.3: http://rpm.pbone.net/index.php3?stat=3&srodzaj=1&dl=40&search=php-pecl-libsodium&field[]=1&field[]=2

Surely, the reported version here can't be right?
