### ISSUE TITLE
More open_basedir fun

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#87]
Ref: https://github.com/jasonhinkle/php-gpg/issues/23

Apparently we're still throwing an `E_WARNING`.

**Comment by oucil** [comment]
Thanks @paragonie-scott, FYI, looks like PHPASS also had this issue and simply supressed the `is_readable()` call...

https://github.com/jenssegers-deprecated/codeigniter-phpass-library/commit/d2f1d65f049cb4db94e0a79aa1352d9a29f41d4d

I haven't inspected your call yet, but I'm assuming there's a gracefull fallback when /dev/urandom isn't readable?  This would at least let us plan the deployment with the fallback in use for now.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/blob/1f0018fd968b41bda5a53bdec21a09880e645c6e/lib/random.php#L70

That's exactly what we're doing.

**Comment by oucil** [comment]
Yeah, just noticed that. Hmm, I'll double check that there isn't something at my end ignoring the suppression in our error logger.

**Comment by AshleyPinner** [comment]
@oucil As an aside, letting PHP read `/dev/urandom` is generally a good and safe idea, and would be preferable in this case. Though if you were running PHP 5.5+ you'd also have to make sure PHP itself could read `/dev/urandom` anyway.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/144415fe86991730ac53e727abf3701b60295607 This ought to do the trick.

What it did before:

* Use `@is_readable()`

What it does now:

* Short-circuit the logic if we're not on a Unix-like OS.
* See if open_basedir isn't empty. If it's not empty, it makes sure that `/dev` is one of the allowed paths.
* FInally, use `@is_readable()` so we fail in the case of weird setups that somehow block it still (chroot jails?).

**Comment by oucil** [comment]
No luck yet, we're using `if (error_reporting() === 0) { return; }` in our custom error handler, so it *should* be ignoring the notice entirely.  I'll spend a few more minutes on this, but it looks like it's at my end anyway, so thanks for your help.  Failing the above, I'm definitely going to open up `/dev/urandom`, just avoiding pain ;)

P.S. thanks for the above will check it out.

**Comment by paragonie-scott** [comment]
https://stackoverflow.com/questions/21427211/check-if-open-basedir-restriction-is-in-effect#comment32326915_21427311

It looks like `open_basedir` ignores error suppression.

**Comment by oucil** [comment]
@paragonie-scott I like the commit, good workaround to avoid the notices. I'm going both routes, updating our AMI's and opening up the basedir restriction, and will incorporate the changes above (unless you're going to tag another release?).  Thanks for your help!

**Comment by paragonie-scott** [comment]
I'm going to roll this into 1.1.6 shortly.

I try to, barring emergencies, give changes a minimum 24 hours to sit before I tag a release just to give other contributors a chance to tell me, "Hey, you probably should reconsider this specific change."

If anyone ever discovered a critical security bug, it would get rolled out as soon as possible.

**Comment by oucil** [comment]
Wise move :)  Thanks again!

**Comment by philios33** [comment]
Is there a problem with using just `@is_readable('/dev/urandom')` ? I only ask because I cant see any discussion about the problem it is causing with open_basedir.  On my environment it is returning correctly (true or false) depending on whether it is in open_basedir.

**Comment by paragonie-scott** [comment]
We tried, it was still raising an `E_WARNING` error.

**Comment by philios33** [comment]
Do we know if it is due to a custom error handler which doesn't check the error_reporting value?  Because it should be [returning 0 when the @ operator is used](http://php.net/manual/en/language.operators.errorcontrol.php)

**Comment by oucil** [comment]
@philios33 If you read the thread above you'll see we had the  `if (error_reporting() === 0) { return; }` check in place.

**Comment by philios33** [comment]
Sorry my misunderstanding. Didn't see you were talking about the handler.
