### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by relaxnow** [paragonie/random_compat#89]
As an auditor I would like to see a CHANGELOG though to quickly see what a new version contains.

**Comment by sergeyklay** [comment]
+1

**Comment by glensc** [comment]
while at it, have look at recommendation: http://keepachangelog.com/

**Comment by paragonie-scott** [comment]
I've been *sort of* doing that here: https://github.com/paragonie/random_compat/releases 

But on the other hand, not everyone uses Github. Let me see if I have time this evening to make it happen.

**Comment by glensc** [comment]
what i practice is update changelog.md constantly (after each change), and when making  the release, copy appropriate block from changelog.md to github releases page.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/b3f8c8905b2c1aec53a0eedd4ed1c8d7ee2305a1

**Comment by sergeyklay** [comment]
@paragonie-scott Good work! :+1:
