### ISSUE TITLE
mcrypt_create_iv hangs (possibly a PHP 5.6.10-12 bug)

### ISSUE THREAD

**Issue by philios33** [paragonie/random_compat#90]
If /dev/urandom is not readable, there is no point in trying to use mcrypt with the MCRYPT_DEV_URANDOM flag as a fallback.  On my system the mcrypt extension actually hangs at 100% CPU forever.

**Comment by paragonie-scott** [comment]
I want to call this a PHP bug. https://github.com/paragonie/random_compat/commit/8d7e80cc049081c3b2b14beff573f85e7b22e744 should work around it, though.

**Comment by paragonie-scott** [comment]
https://bugs.php.net/bug.php?id=71679

**Comment by philios33** [comment]
Thanks for reporting it to PHP.  Yes I would agree, if it turns out to really be an open_basedir problem.  

Commit looks good for this particular bug.  

If I understand this correctly, to use mcrypt on linux we need to have access to urandom.  That commit pretty much makes the mcrypt fallback redundant on linux cases.  If there is readable access to urandom, it would read it directly.  So actually it is good to keep mcrypt fallback for windows. (I forgot about windows).

**Comment by yohgaki** [comment]
@paragonie-scott 
I updated the bug comment. I couldn't reproduce the delay. System specific maybe? I'm using Fedora23 x64.

**Comment by dd32** [comment]
I'm fairly certain that `mcrypt_create_iv(16, MCRYPT_DEV_URANDOM);` doesn't respect open_basedir (Reading the PHP source seems to agree with this, although I'm not sure how open_basedir is actually implemented there), however I think I've seen reports before that some environments which use open_basedir also don't have a readable/reliable /dev/urandom file.

Looking at the PHP source of mcrypt, if it's hanging at 100% CPU, that would have to suggest that it's run out of entropy and [endlessly trying to read from `/dev/urandom`](https://github.com/php/php-src/blob/PHP-5.6.19/ext/mcrypt/mcrypt.c#L1463-L1469). I can duplicate 100% CPU if I create a static `/dev/urandom` file to simulate that out-of-entropy state.

**Comment by cs278** [comment]
> Looking at the PHP source of mcrypt, if it's hanging at 100% CPU, that would have to suggest that it's run out of entropy and endlessly trying to read from /dev/urandom. I can duplicate 100% CPU (& timeouts) if I create a static /dev/urandom file to simulate that out-of-entropy state.

I concur. There are no open_basedir checks inside `mcrypt_create_iv`, and I cannot replicated it on Debian x64 with various PHP's. Per @dd32 the only way I've found to replicate the problem is to have a `/dev/urandom` that runs out of bytes which causes nothing being read infinitely.

@philios33 What do you get from `stat /dev/{,u}random`?

**Comment by paragonie-scott** [comment]
Interesting. I would be very happy to hear that I can close https://bugs.php.net/bug.php?id=71679 as invalid. :)

**Comment by philios33** [comment]
My Environment:

OS: Cent OS
cat /etc/redhat-release
CentOS release 6.7 (Final)

Server Version: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips
Server MPM: event

PHP Version 5.6.12
PHP Extension Build 	API20131226,TS,debug 

mcrypt support	enabled
mcrypt_filter support	enabled
Version 	2.5.8
Api No 	20021217 

open_basedir = <webroot>:/tmp

stat /dev/{,u}random

 File: `/dev/random'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 5h/5d   Inode: 3849        Links: 1     Device type: 1,8
Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-02-26 19:46:32.980000002 +0100
Modify: 2016-02-26 19:46:32.980000002 +0100
Change: 2016-02-26 19:46:32.980000002 +0100
  File: `/dev/urandom'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 5h/5d   Inode: 3850        Links: 1     Device type: 1,9
Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-02-26 19:46:32.981000002 +0100
Modify: 2016-02-26 19:46:32.981000002 +0100
Change: 2016-02-26 19:46:32.981000002 +0100

**Comment by philios33** [comment]
I get this issue with wordpress 4.4.2 so I'm not using latest build but I have tried, just out of curiosity, to force mcrypt fallback and even with /dev/urandom in the open_basedir, it still hangs.  So I can confirm this problem isn't to do with open_basedir and is looking more like an issue with mcrypt itself.  

The real reason adding /dev/urandom to my open_basedir fixed the problem is because it never got to the mcrypt fallback because @is_readable(/dev/urandom) returned true instead of false.

**Comment by paragonie-scott** [comment]
@philios33 https://bugs.php.net/bug.php?id=69833 Possibly related?

**Comment by philios33** [comment]
Perhaps, although I never get the maximum execution time error, it just hangs forever until I restart apache.

I tried
`<?php
set_time_limit(10);
$iv = mcrypt_create_iv(16, MCRYPT_DEV_URANDOM);
var_dump(bin2hex($iv));`
from the command line and it works just fine.
[root@php1 public_html]# php mcrypt_test.php
string(32) "f9812a78adf5e446d1fb0c29d7db62ba"
but hangs when requested via apache

Is there any way I can test whether it is actually an entropy problem?  Is there anything I can run on the server to create entropy while it is hanging to see if I can get it to errr "unhang"?

**Comment by philios33** [comment]
That bug was fixed in 5.6.13 (typical).  I'm going to recompile to PHP 5.6.18 and get back to you.

**Comment by paragonie-scott** [comment]
To prevent this from biting people, it looks like we should block mcrypt when:

    PHPVERSIONID >= 50610 && PHPVERSIONID <= 50613

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/8d7dd3479ffca1cce42d4d903f09ba9185edde19

**Comment by philios33** [comment]
Confirmed fixed in PHP 5.6.18.

**Comment by paragonie-scott** [comment]
Excellent news. :+1:
