### ISSUE TITLE
Exception: "Could not gather sufficient random data"

### ISSUE THREAD

**Issue by truckee** [paragonie/random_compat#91]
In a Symfony application the following error appears when attempting to go to any of several URIs:

> 
request.CRITICAL: Uncaught PHP Exception Exception: "Could not gather sufficient random data" at /www2.projectmana.org/vendor/paragonie/random_compat/lib/random_bytes_mcrypt.php line 73 {"exception":"[object] (Exception(code: 0): Could not gather sufficient random data at /www2.projectmana.org/vendor/paragonie/random_compat/lib/random_bytes_mcrypt.php:73)"} []

The application is hosted on a site with freebsd, PHP 5.6.18.  Symfony is 2.8.3.  I am unable to reproduce the error on a Windows 10 system with same PHP , Symfony & application source code versions.  A posting on Stackoverflow regarding this error is without any response as of this writing.  Can you advise?

**Comment by paragonie-scott** [comment]
It means precisely what it says: Something about your environment is preventing `mcrypt_create_iv($numBytesRequested, MCRYPT_DEV_URANDOM)` from generating enough entropy.

Make sure PHP can read `/dev/urandom`, especially if you're in a chroot jail. Without access to the kernel's CSPRNG, we cannot reliably generate random data suitable for cryptography.

**Comment by truckee** [comment]
Thank you for your quick reply.  I have forwarded your comment to the host of the site.  Much appreciated.

**Comment by truckee** [comment]
@paragonie-scott Thank you again.  The host has tuned us up and the error is gone.
