### ISSUE TITLE
lib/random.php should include a version number

### ISSUE THREAD

**Issue by ocean90** [paragonie/random_compat#92]
For software like WordPress which bundles the library it's currently not easy to identify which version the library has. I propose to add the version number to the header in lib/random.php.

**Comment by paragonie-scott** [comment]
As a constant or just a string in a docblock?

**Comment by ocean90** [comment]
A string in the doc block would be sufficient IMO.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/blob/master/lib/random.php#L6-L7

Going forward, I'll update this before issuing a release.

**Comment by GrahamCampbell** [comment]
:-1: for this - it's just a massive pain to keep up to date, and very confusing if a release ships where it's forgotten to be updated

**Comment by paragonie-scott** [comment]
@GrahamCampbell Normally I'd agree, but development has slowed significantly (due to stability, and distinctly not staleness or lack of interest) and I don't foresee a great deal of new development being done.

**Comment by narfbg** [comment]
If you happen to be using scripts to help with release-related tasks, a check in there could help with not forgetting to update the version number.

**Comment by paragonie-scott** [comment]
As of 1.2.2 this is implemented. Since I have to take the time to sign the release anyway, I'll probably not forget to do this step.

**Comment by mbabker** [comment]
And it wasn't updated in any of the releases after 1.2.2 :stuck_out_tongue:

**Comment by paragonie-scott** [comment]
Sigh, yeah

**Comment by GrahamCampbell** [comment]
> And it wasn't updated in any of the releases after 1.2.2 :stuck_out_tongue:

Said that would happen, lol.

**Comment by paragonie-scott** [comment]
OK, 1.4.1 and 2.0.1 have it.
