### ISSUE TITLE
ERRATA.md incorrect advice about /dev/urandom

### ISSUE THREAD

**Issue by sthen** [paragonie/random_compat#95]
From ERRATA.md: "On Unix-based operating systems, it reads from /dev/urandom, which is the sane and correct thing to do."

This is not the sane and correct thing to do when a better API is available (getentropy(), getrandom(), the deprecated linux sysctl, or an arc4random() implementation backed by one of these - with /dev/urandom, opening of the device node can fail: out of file handles, program running in chroot.

In particular: if an attacker can cause too many FDs to be open, that would be Very Bad if you're relying on entropy from /dev/urandom.

**Comment by paragonie-scott** [comment]
"The sane and correct thing to do" was in contrast to [`/dev/random`](http://www.2uo.de/myths-about-urandom/).

> This is not the sane and correct thing to do when a better API is available (getentropy(), getrandom(), the deprecated linux sysctl, or an arc4random() implementation backed by one of these

And which of those can we do from PHP?

**Comment by sthen** [comment]
Whichever is supported by libsodium. I do agree with the choices and ordering you've made, but calling /dev/urandom "sane and correct" might make some people think "oh that's ok then, if this is safe I won't bother to install libsodium"...

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/abe5c4aa4fac4362345224982ea672f033bb7d59

Is this a significant improvement?

**Comment by sthen** [comment]
Yes, that is better, thank you Scott.

**Comment by paragonie-scott** [comment]
Version 1.2.2 ships with this improvement. Thanks for the suggestion. :+1:
