### ISSUE TITLE
What to do about OpenSSL?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/random_compat#96]
* [It's not fork safe](https://github.com/ramsey/uuid/issues/80)
* [In most versions of PHP, it lies about being secure](https://bugs.php.net/bug.php?id=70014)
* And today I learned that OpenSSL, by default (i.e. unchangable from PHP land) [uses MD5 as a CSPRNG](https://wiki.openssl.org/index.php/Random_Numbers#Generators) (thanks @atoponce)

I'm stuck between several possible avenues:

* Release a new version (v1.3.0 or most likely v2.0.0) that doesn't rely on OpenSSL at all
* Create an OpenSSL-free fork, called secure_random
* Possibly in either case allow LibreSSL/BoringSSL but definitely not OpenSSL

I'm interested in everyone's opinions here. The status quo is simply unacceptable.

**Comment by narfbg** [comment]
Kill it.

**Comment by ivantcholakov** [comment]
v2.0.0 that doesn't rely on OpenSSL at all seems to be the best choice.

**Comment by GrahamCampbell** [comment]
:+1: For killing it in a 2.0.0 release.

**Comment by GrahamCampbell** [comment]
Though, actually, given the seriousness, I'm inclined to say that actually a 1.3.0 is a better bet to ensure this gets widely deployed, quickly.

**Comment by paragonie-scott** [comment]
http://semver.org/ dictates a major version increment with an incompatible API change, which removing support for OpenSSL almost certainly is

**Comment by narfbg** [comment]
This is not an API change.

In fact, the *public* API (and semver.org does always say "public API") is tied to PHP 7.0.0's, so you almost by definition can't break SemVer compatibility.

**Comment by GrahamCampbell** [comment]
That's true, which is why my first comment was for 2.0.0, but on reflection, I think 1.3.0 is better, despite semver for the reasons I said already. Most applications are restricting the version to 1.x for this package.

I agree with @narfbg in terms of saying this isn't actually a break. Only the internal API has changed.

**Comment by paragonie-scott** [comment]
Right. And the area where the issue is most likely going to occur is in WordPress, which already catches the Exception and falls back to what they used previously.

Unless anyone objects I'm going to roll out 1.3.0 without OpenSSL.

**Comment by ivantcholakov** [comment]
No objection about 1.3.0 from me.

**Comment by ramsey** [comment]
@paragonie-scott, I'm curious about your thoughts on a better CSPRNG to use in PHP, given your [RFC (currently in voting phase) to kill mcrypt](https://wiki.php.net/rfc/mcrypt-viking-funeral) and our concerns with OpenSSL. Is there a better library we should eventually move into the PHP core that provides the same (yet more secure) functionality (i.e. LibreSSL, libsodium, etc.)?

**Comment by paragonie-scott** [comment]
@ramsey Yes, for a CSPRNG, it's called `random_bytes()` and it's part of the PHP 7 core.

The water is muddy here: `mcrypt_create_iv()` is the only ext/mcrypt function that's sanely implemented. On the flipside, `openssl_random_pseudo_bytes()` is the only ext/openssl function that's insanely implemented.

CSPRNG aside, libsodium (which random_compat prefers if it's available) is highly regarded by cryptography/security experts. I have another RFC to add libsodium to PHP in 7.1, pending some changes after 1.0.3 of the PHP extension (which will sync up with 1.0.9 of the library) is finished.

**Comment by paragonie-scott** [comment]
To clarify, the post-1.0.3 changes are API related but functionally zero: Instead of `\Sodium\function_here()` it will be accessed via `sodium_function_here()`. A congruent change will be made to the constants.

**Comment by GrahamCampbell** [comment]
> Right. And the area where the issue is most likely going to occur is in WordPress

Can't say I'm that bothered :trollface:

**Comment by ramsey** [comment]
> Yes, for a CSPRNG, it's called random_bytes() and it's part of the PHP 7 core.

Well, obviously! ;-)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/1c435ec2c4c48a2d9a3ba405b5418c8b7ce708ef removes OpenSSL. I'll tag/sign a release on Friday.

**Comment by AshleyPinner** [comment]
Just to weigh in here, while I agree that the other reasons are good ones to remove it, OpenSSL doesn't actually use MD5 for the RAND calls. It's not much better, but [by default in 1.0.1 it seems to be using SHA1](https://github.com/openssl/openssl/blob/349807608f31b20af01a342d0072bb92e0b036e2/crypto/rand/rand_lcl.h#L116) (Unless you explicitly build it to use MD5... or less...). 

A quick check of the compile options (Use `openssl version -a` to see them all) should tell you if you're using a version compiled with explicit `USE_MD5_RAND` or not. CentOS 7 & 6, Ubuntu 14.04 seem not to define it, and I'd love to know if any OpenSSL 1.0.x builds define it.

**Comment by kaystrobach** [comment]
will there be an 1.4.x tag which is not listed on sensio labs (e.g. with openssl disabled?)

**Comment by paragonie-scott** [comment]
That's what v2.x is.

**Comment by andrerom** [comment]
@paragonie-scott Is it correct to say this is not affecting [PHP 5.6.24  and higher](https://github.com/php/php-src/commit/0e2447cd11f4b72257e5d2609f923177e9736c3c)?

Asking in regards to same above, the listing on [security-advisories](https://github.com/FriendsOfPHP/security-advisories/issues/259#issuecomment-369274526)

**Comment by kaystrobach** [comment]
@paragonie-scott - thanks just created an pull request in neos/flow 3.3 to switch to v2 ... thanks a lot

**Comment by paragonie-scott** [comment]
@andrerom I believe so. However, the decision to trust a userspace PRNG rather than the kernel's CSPRNG was a mistake that we will never repeat.

**Comment by andrerom** [comment]
Clear, I was more thinking a 1.5 release bumping php requirements would allow security advisories to avoid blindly marking whole 1.x branch as insecure, when in fact it depends.

**Comment by paragonie-scott** [comment]
Honestly, just upgrade to v2.x. Other than the OpenSSL drop, there are no other significant changes.

**Comment by kaystrobach** [comment]
I just did it for 2 projects, works like a charm - thanks a lot.

**Comment by paragonie-scott** [comment]
Awesome! If anyone else stumbles over this, I've just updated the readme to use headers instead of bold text so you can link folks directly to the relevant section: https://github.com/paragonie/random_compat/blob/master/README.md#version-conflict-with-other-php-project
