### ISSUE TITLE
1.3 release

### ISSUE THREAD

**Issue by GrahamCampbell** [paragonie/random_compat#97]
Can I just check when you plan to release 1.3 please. I am prepping security patches for laravel branches, old and new, to switch them over to `~1.3` (some of which still don't use this package at all yet).

**Comment by xabbuh** [comment]
Looks like a release is planned for tomorrow: https://github.com/paragonie/random_compat/issues/96#issuecomment-197664616

**Comment by GrahamCampbell** [comment]
Ok. ;)

**Comment by paragonie-scott** [comment]
If there's a pressing need to get it out today, I can release it now. I just thought I would need more time to update the tests and documentation.

**Comment by GrahamCampbell** [comment]
Well, we'd like to be able to ship patches to Laravel ASAP. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/12763
https://github.com/laravel/framework/pull/12764
https://github.com/laravel/framework/pull/12765

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/releases/tag/v1.3.0

**Comment by GrahamCampbell** [comment]
Thank you. :)
